spring:
  application:
    name: SpringTest

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    default-schema: spring_test