openapi: 3.0.3
info:
  title: Shop API
  version: 1.0.0

tags:
  - name: user-controller
    description: Управление пользователями и их заказами
  - name: warehouse-controller
    description: Управление складами и товарами

paths:
  /api/v1/users:
    post:
      tags:
        - user-controller
      summary: Создать пользователя вместе с его заказами
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateDto'
      responses:
        '201':
          description: Пользователь и заказы успешно созданы
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDto'

    get:
      tags:
        - user-controller
      summary: Получить список пользователей с вложенными заказами
      operationId: getAllUsers
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
          description: Номер страницы
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Количество пользователей
      responses:
        '200':
          description: Список успешно получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponseDto'

  /api/v1/users/{id}:
    get:
      tags:
        - user-controller
      summary: Получить пользователя по ID с его заказами
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Пользователь найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDto'

    put:
      tags:
        - user-controller
      summary: Обновить данные пользователя и его заказов
      operationId: updateUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateDto'
      responses:
        '200':
          description: Данные успешно обновлены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDto'

    delete:
      tags:
        - user-controller
      summary: Удаленить пользователя и его заказы
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Пользователь и его заказы успешно удалены

  /api/v1/warehouses:
    post:
      tags:
        - warehouse-controller
      summary: Создать склад вместе с товарами
      operationId: createWarehouse
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WarehouseCreateDto'
      responses:
        '201':
          description: Склад успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarehouseResponseDto'
    get:
      tags:
        - warehouse-controller
      summary: Получить список складов с товарами
      operationId: getAllWarehouses
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Список складов получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WarehouseResponseDto'

  /api/v1/warehouses/{id}:
    get:
      tags:
        - warehouse-controller
      summary: Получить склад по ID со всеми товарами
      operationId: getWarehouseById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Склад найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarehouseResponseDto'
    put:
      tags:
        - warehouse-controller
      summary: Обновить склад и список его товаров
      operationId: updateWarehouse
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WarehouseUpdateDto'
      responses:
        '200':
          description: Склад обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarehouseResponseDto'
    delete:
      tags:
        - warehouse-controller
      summary: Мягкое каскадное удаление склада и его связей с товарами
      operationId: deleteWarehouse
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Склад успешно удален

components:
  schemas:
    UserCreateDto:
      type: object
      required:
        - username
      properties:
        username:
          type: string
        orders:
          type: array
          items:
            $ref: '#/components/schemas/OrderCreateDto'

    OrderCreateDto:
      type: object
      required:
        - description
      properties:
        description:
          type: string

    UserUpdateDto:
      type: object
      required:
        - username
      properties:
        username:
          type: string
        orders:
          type: array
          items:
            $ref: '#/components/schemas/OrderUpdateDto'

    OrderUpdateDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Если ID передан — обновляем существующий заказ, если нет — создаем новый внутри пользователя
        description:
          type: string

    UserResponseDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        orders:
          type: array
          items:
            $ref: '#/components/schemas/OrderResponseDto'

    OrderResponseDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        description:
          type: string

    WarehouseCreateDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductCreateDto'

    ProductCreateDto:
      type: object
      required:
        - title
        - price
      properties:
        title:
          type: string
        price:
          type: number

    WarehouseUpdateDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductUpdateDto'

    ProductUpdateDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        price:
          type: number

    WarehouseResponseDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductResponseDto'

    ProductResponseDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        price:
          type: number